version: "3.8"

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: mypassword
            POSTGRES_USER: myuser
            POSTGRES_DB: mydatabase
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_data: # Named volume to persist data
