version: "3.8"

services:
    postgres-eCommerce-user:
        image: postgres:latest
        container_name: postgres-eCommerce-user
        environment:
            POSTGRES_PASSWORD: eCommerce-user-password
            POSTGRES_USER: eCommerce-user-username
            POSTGRES_DB: eCommerce-user-database
        volumes:
            - postgres_eCommerce_user:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_eCommerce_user: # Named volume to persist user data
