version: "3.8"

services:
    postgres-eCommerce-product:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: eCommerce-product-password
            POSTGRES_USER: eCommerce-product-username
            POSTGRES_DB: eCommerce-product-database
        volumes:
            - postgres_eCommerce_product:/var/lib/postgresql/data
        ports:
            - "5433:5432"

volumes:
    postgres_eCommerce_product: # Named volume to persist data
